### ISSUE TITLE
Getting a 400 Error on the DFP requests

### ISSUE THREAD

**Issue by markcarey** [coop182/jquery.dfp.js#111]
I have 2 ad units on the page, and they don't load.

In safari, I see the follow error in console for each:

    Failed to load resource: the server responded with a status of 400 (Bad Request)

URL requested is like (I have replaced identifying info and replaced the DFPid with XXXXXXX:

https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&correlator=3779269110005760&output=json_html&callback=callbackProxy&impl=fif&eid=108809080%2C108809049&sc=0&sfv=1-0-2&iu=%2FXXXXXXX%2FAd_Unit_Name&sz=960x0&cust_params=UrlHost%3Ddomain.com%252Cdomain.com%26UrlPath%3D%252Ffile-name.php%252C%252Ffile-name.php%26UrlQuery%3D&cookie=ID%3Df6c5a6b44c82b8f6%3AT%3D1415104988%3AS%3DALNI_MZZvAlvhI1KblUjxGWRbm3zKiTufw&lmt=1443721122&dt=1443706722796&cc=100&frm=20&biw=1383&bih=884&oid=3&adx=212&ady=2690&adk=1055041421&gut=v2&ifi=4&u_tz=-240&u_his=3&u_java=true&u_h=1080&u_w=1920&u_ah=1057&u_aw=1885&u_cd=24&u_nplug=16&u_nmime=105&u_sd=1&flash=19.0.0&url=http%3A%2F%2Fdomain.com%2Ffile-name.php&dssz=98&icsg=559776&std=11&vrg=73&vrp=73&ga_vid=107901648.1245432157&ga_sid=1443706720&ga_hid=1713498263&ga_fc=true

Not sure if it is relevant, but the ads being served in these units are custom creatives that contain javascript blocks.

**Comment by Preen** [comment]
are you certain about the ID? I had the same error but after checking the ID and matched it with a correct one I got it working!

**Comment by Preen** [comment]
Sorry was wrong, I'm having the same issue...

**Comment by adamgamble** [comment]
I'm also having this issue. I *think* I had it previously and fixed it by removing other google adsense code on the page (from an old ad setup) and using jquery dfp exclusively. However I think i'm having this problem again on a different site and I think I've removed all the old adsense code.

**Comment by coop182** [comment]
If any of you have an example URL where this is happening that I can view can you please share it here... or email it to me at matt@matthewcooper.net if you don't want to have it in public

**Comment by adamgamble** [comment]
@coop182 Actually I just fixed it. (disregard my email). The problem was I hadn't set the data dimensions.

**Comment by coop182** [comment]
Cool... I just had a look and it was working so that was confusing haha.... glad you got it working! :smile: 
@markcarey or @Preen if you want me to take a look at your URL's just let me know.

**Comment by adamgamble** [comment]
thanks for your help!

**Comment by gctommy** [comment]
@markcarey — did you ever resolve this?

We are running into the same issue, have data-dimensions set correctly, but still get the 400 (Bad Request) error occasionally coming back with all with blank ads.
